usercrud/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^userregister/', include('userregister.urls')),
    url(r'^admin/', admin.site.urls),
]

userregister/urls.py
from django.conf.urls import url
from . import views

app_name="userregister"
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<user_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^new/$', views.new, name='new'),
	url(r'^update/$', views.update, name="update"),
	url(r'^(?P<user_id>[0-9]+)/delete/$', views.delete, name="delete"),
	url(r'^save/$', views.save, name='save'),
]

userregister/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User(models.Model):
	username = models.CharField(max_length=30)
	password = models.CharField(max_length=30)
	secr_question = models.CharField(max_length=30)
	secr_answer = models.CharField(max_length=30)

	def __str__(self):
		return self.username

	def __str__(self):
		return self.password

	def __str__(self):
		return self.secr_question

	def __str__(self):
		return self.secr_answer

userregister/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import User


def index(request):
    user_list = User.objects.all()
    context = {
    	'user_list': user_list,
    }
    return render(request, 'userregister/index.html', context)


def detail(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	return render(request, "userregister/detail.html", {'user': user})

def new(request):
	return render(request, "userregister/new.html")

def save(request):
	name = request.POST['username']
	passw = request.POST['password']
	secquest = request.POST['question']
	secansw = request.POST['answer']
	q = User(username=name, password=passw, secr_question=secquest, secr_answer=secansw)
	q.save()
	return HttpResponseRedirect(reverse('userregister:index'))

def update(request):
	ide = request.POST['userid']
	name = request.POST['username']
	passw = request.POST['password']
	secquest = request.POST['question']
	secansw = request.POST['answer']
	q = User(id=ide, username=name, password=passw, secr_question=secquest, secr_answer=secansw)
	q.save()
	return HttpResponseRedirect(reverse('userregister:index'))

def delete(request, user_id):
	q = User.objects.get(pk=user_id)
	q.delete()
	return HttpResponseRedirect(reverse('userregister:index'))

userregister/templates/userregister/base.html
<html>

userregister/templates/userregister/detail.html
<h1>{{ user.id }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form method="post" action="{% url 'userregister:update' %}">
{% csrf_token %}
	<input type="hidden" id="userid" name="userid" value="{{ user.id }}"/>
	<input type="text" id="username" name="username" value="{{ user.username }}"/><br/>
	<input type="password" id="password" name="password" value="{{ user.password}}"/><br/>
	<input type="text" id="question" name="question" value="{{ user.secr_question }}"/><br/>
	<input type="text" id="answer" name="answer" value="{{ user.secr_answer }}"/><br/>
	<input type="submit" id="update" value="Actualizar"/>
</form>

userregister/templates/userregister/index.html
<a href="{% url 'userregister:new' %}">Nuevo</a>
{% if user_list %}
	<table>
		<thead>
			<td><b>Nombre de usuario</b></td><td><b>Pregunta secreta</b></td><td><b>Acciones</b></td>
		</thead>
		<tbody>
		{% for user in user_list %}
			<tr>
				<td>{{ user.username }}</td>
				<td>{{ user.secr_question }}</td>
				<td><a href="{% url 'userregister:detail' user.id %}">Editar</a>&nbsp;
					<a href="{% url 'userregister:delete' user.id %}">Borrar</a></td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% else %}
<p>No users in database </p>
{% endif %}

userregister/templates/userregister/new.html
<form method="post" action="{% url 'userregister:save' %}">
{% csrf_token %}
	nombre de usuario: <input type="text" id="username" name="username"/><br/>
	clave: <input type="password" id="password" name="password"/><br/>
	pregunta secreta: <input type="text" id="question" name="question"/><br/>
	respuesta secreta: <input type="text" id="answer" name="answer"/><br/>
	<input type="submit" id="save" value="Guardar"/>
</form>